# Generated by Django 4.0.6 on 2022-08-10 17:15

import debtors.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('image', models.FileField(upload_to=debtors.models.get_article_image_filepath)),
                ('document', models.FileField(upload_to=debtors.models.get_article_filepath)),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=200)),
                ('stclass', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Debtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_class', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('debtor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('debtors_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.debtors')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=debtors.models.get_profile_image_filepath)),
                ('location', models.TextField()),
                ('CAC', models.IntegerField()),
                ('certificate', models.FileField(upload_to='')),
                ('Local_government', models.CharField(max_length=200)),
                ('school', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('status', models.CharField(max_length=200)),
                ('proofofpayment', models.FileField(upload_to=debtors.models.get_Contendproof_filepath)),
                ('debt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.debt')),
                ('debtor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.debtors')),
            ],
        ),
        migrations.AddField(
            model_name='debtors',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.school'),
        ),
        migrations.CreateModel(
            name='DebtorComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('debtor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.debtors')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.school')),
            ],
        ),
        migrations.AddField(
            model_name='debt',
            name='School_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.school'),
        ),
        migrations.AddField(
            model_name='debt',
            name='debtor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.debtors'),
        ),
        migrations.CreateModel(
            name='ArticleComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.article')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.school')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.school'),
        ),
    ]
