# Generated by Django 4.0.6 on 2022-08-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('image', models.FileField(upload_to='')),
                ('document', models.FileField(upload_to='')),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=200)),
                ('stclass', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(max_length=200)),
                ('proofofpayment', models.FileField(upload_to='')),
                ('debt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.debt')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='school_id',
        ),
        migrations.DeleteModel(
            name='Contend',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='school_class',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='student',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='debtors',
            name='info',
        ),
        migrations.RemoveField(
            model_name='school',
            name='certificate',
        ),
        migrations.AddField(
            model_name='debtors',
            name='student_class',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debtors',
            name='student_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='CAC',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='Local_government',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='debtors_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='debtors.debtors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='school_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='debtors.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debtors',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='dispute',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='debtors.school'),
        ),
        migrations.AddField(
            model_name='article',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.school'),
        ),
    ]
