# Generated by Django 4.0.6 on 2022-08-10 16:45

import debtors.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0002_article_debt_dispute_remove_comment_school_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='dispute',
            old_name='comment',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='debtors',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_id',
        ),
        migrations.AddField(
            model_name='debt',
            name='School_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='debtors.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='debtor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='debtors.debtors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debtors',
            name='info',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispute',
            name='debtor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='debtors.debtors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='certificate',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='document',
            field=models.FileField(upload_to=debtors.models.get_article_filepath),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to=debtors.models.get_article_image_filepath),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.school'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='proofofpayment',
            field=models.FileField(upload_to=debtors.models.get_Contendproof_filepath),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(upload_to=debtors.models.get_profile_image_filepath),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DebtorComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('debtor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.debtors')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.school')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.article')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.school')),
            ],
        ),
        migrations.AddField(
            model_name='debtors',
            name='debtor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
