# Generated by Django 4.0.6 on 2022-08-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0005_account_groups_account_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='school_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='debtors.school'),
            preserve_default=False,
        ),
    ]
