# Generated by Django 4.0.6 on 2022-08-05 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_pay', models.FileField(upload_to='')),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Debtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('student', models.IntegerField()),
                ('student_class', models.CharField(max_length=200)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('CAC', models.IntegerField()),
                ('certificate', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('debtors_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.debtors')),
            ],
        ),
        migrations.AddField(
            model_name='debtors',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.school'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.school')),
            ],
        ),
    ]
